/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include "W3SIncs/War3Source_Interface"

public Plugin:myinfo = 
{
	name = "WCX - Crit/Damage Engine",
	author = "necavi",
	description = "WCX Critical strike and extra damage engine",
	version = "0.1",
	url = "http://0xf.org"
}

public OnPluginStart()
{
	
}

public OnW3TakeDmgAllPre(victim, attacker, Float:damage)
{
	new Float:CritChance = W3GetBuffSumFloat(attacker, fCritChance);
	new Float:DamageMultiplier = W3GetBuffSumFloat(attacker, fDamageModifier);
	if(DamageMultiplier > 1.0)
	{
		new DamageMode = W3GetBuffMinInt(attacker, iDamageMode);
		decl String:weapon[64];
		GetEventString(W3GetVar(SmEvent),"weapon",weapon,63);
		switch(DamageMode)
		{
			//Default 0 (all damage qualifies for damage increase)
			case(0):{
				War3_DamageModPercent(DamageMultiplier);
			}
			//1 (bullet damage damage increase)
			case(1):{
				if(!W3IsDamageFromMelee(weapon) && !StrEqual(weapon,"hegrenade",false))
					War3_DamageModPercent(DamageMultiplier);
			}
			// 2 (grenade damage damage increase) 
			case(2):{
				if(StrEqual(weapon,"hegrenade",false))
					War3_DamageModPercent(DamageMultiplier);
			}
			//3 (melee damage damage increase)
			case(3):{
				if(W3IsDamageFromMelee(weapon))
					War3_DamageModPercent(DamageMultiplier);
			}
			//4 (melee and bullet damage increase)
			case(4):{
				if(!StrEqual(weapon,"hegrenade",false))
					War3_DamageModPercent(DamageMultiplier);
			}
			//5 (melee and grenade damage increase) 
			case(5):{
				if(StrEqual(weapon,"hegrenade",false)||W3IsDamageFromMelee(weapon))
					War3_DamageModPercent(DamageMultiplier);
			}
			//6 (bullet and grenade damage increase)
			case(6):{
				if(StrEqual(weapon,"hegrenade",false)||!W3IsDamageFromMelee(weapon))
					War3_DamageModPercent(DamageMultiplier);
			}
		}
	}
	
}




