/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include "W3SIncs/War3Source_Interface"

new PlayerRace[MAXPLAYERSCUSTOM];

public Plugin:myinfo = 
{
	name = "WCX Bash",
	author = "necavi",
	description = "WCX Bash",
	version = "0.1",
	url = "http://necavi.com"
}

public OnPluginStart()
{
	LoadTranslations("w3s.race.human.phrases");
}

public OnWar3EventPostHurt(victim,attacker,damage){
	if(IS_PLAYER(victim)&&IS_PLAYER(attacker)&&victim>0&&attacker>0&&attacker!=victim)
	{
		
		new vteam=GetClientTeam(victim);
		new ateam=GetClientTeam(attacker);
		if(vteam!=ateam)
		{
			new Float:percent = W3GetBuffStackedFloat(attacker,fBashChance);
			if((percent < 1.0) && !Hexed(attacker) &&!W3HasImmunity(victim,Immunity_Skills))
			{
				// Bash
				if(GetRandomFloat(0.0,1.0)>=percent && !W3GetBuffHasTrue(victim,bBashed) && IsPlayerAlive(attacker))
				{
					new race=War3_GetRace(victim);
					PlayerRace[victim] = race;
					War3_SetBuff(victim,bBashed,race,true);
					
					W3FlashScreen(victim,RGBA_COLOR_RED);
					CreateTimer(0.25,UnfreezePlayer,victim);
					
					PrintHintText(victim,"%T","RcvdBash",victim);
					PrintHintText(attacker,"%T","Bashed",attacker);
				}
			}
			
		}
	}
}

public Action:UnfreezePlayer(Handle:h,any:victim)
{
	War3_SetBuff(victim,bBashed,PlayerRace[victim],false);
}
