/**
 * File: War3Source.inc
 * Description: Includes used files
 * Author(s): Anthony Iacono  
 */


#undef REQUIRE_EXTENSIONS
#include <tf2>
#include <cstrike>
#include <tf2_stocks>
#define REQUIRE_EXTENSIONS
	
#include <sdktools>
#include <sdktools_functions>

// SourceMod stuff
#include <keyvalues>



// War3Source Includes

#include "W3SIncs/vars"
#include "W3SIncs/cvar"
#include "W3SIncs/forwards"
#include "W3SIncs/natives"
#include "W3SIncs/offsets"
#include "W3SIncs/gameevents"

#include "W3SIncs/racesutils"

#include "W3SIncs/gameframeandtimer"

#include "W3SIncs/menuintro" 




