/**
 * File: War3Source.inc
 * Description: Includes used files
 * Author(s): Anthony Iacono  
 */



#include <tf2>
#include <cstrike>
#include <tf2_stocks>
    
#include <sdktools>
#include <sdktools_functions>

// SourceMod stuff
#include <keyvalues>



// War3Source Includes

#include "W3SIncs/vars"
#include "W3SIncs/cvar"
#include "W3SIncs/forwards"
#include "W3SIncs/natives"
#include "W3SIncs/gameevents"

#include "W3SIncs/menuintro" 
 



