/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include "W3SIncs/War3Source_Interface"

public Plugin:myinfo = 
{
    name = "New Plugin",
    author = "necavi",
    description = "<- Description ->",
    version = "0.1",
    url = "<- URL ->"
}
new Handle:g_hBuffs = INVALID_HANDLE;
new Handle:g_hBuffArray = INVALID_HANDLE;
new Handle:g_hBuffRace = INVALID_HANDLE;
new Handle:g_hBuffSkill = INVALID_HANDLE;
public bool:InitNativesForwards()
{
    CreateNative("War3_AddSkillBuff", Native_War3_AddSkillBuff);
    return true;
}
public OnPluginStart()
{
    g_hBuffs = CreateArray(1);
    g_hBuffArray = CreateArray(32);
    g_hBuffRace = CreateArray(1);
    g_hBuffSkill = CreateArray(1);
}
public Native_War3_AddSkillBuff(Handle:plugin, numParams)
{
    PushArrayCell(g_hBuffRace, GetNativeCell(1));
    PushArrayCell(g_hBuffSkill, GetNativeCell(2));
    PushArrayCell(g_hBuffs, GetNativeCell(3));
    new any:values[GetNativeCell(5)];
    GetNativeArray(4, values, GetNativeCell(5));
    PushArrayArray(g_hBuffArray, values);
}
public OnWar3EventSpawn(client)
{
    new race = War3_GetRace(client);
    InitSkills(client, race);
}
public OnSkillLevelChanged(client, race, skill, newskilllevel)
{
    InitSkills(client, race);
}
public OnWar3EventDeath(victim, client, deathrace)
{
    ResetSkills(victim, deathrace);
}
ResetSkills(client, race)
{
    for(new i = 0; i < GetArraySize(g_hBuffs); i++)
    {
        if(GetArrayCell(g_hBuffRace, i) == race)
        {
            W3ResetBuffRace(client, GetArrayCell(g_hBuffs, i), race);
        }
    }
}
InitSkills(client, race)
{
    for(new i = 0; i < GetArraySize(g_hBuffs); i++)
    {
        if(GetArrayCell(g_hBuffRace, i) == race)
        {
            new skill = War3_GetSkillLevel(client, race, GetArrayCell(g_hBuffSkill, i));
            War3_SetBuff(client, GetArrayCell(g_hBuffs, i), race, GetArrayCell(g_hBuffArray, i, skill));
        }
    }
}




